baseURL = "/"
relativeURLs = true
uglyURLs = true
disablePathToLower = true
languageCode = "en-us"
title = "Swarm Bee Documentation"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Bee Docs"
    url = "/bee-docs/introduction.html"
    weight = 1

[[menu.main]]
    name = "Bee API"
    url = "/bee-docs/API/README.html"
    weight = 2

[[menu.main]]
    name = "Bee Debug API"
    url = "/bee-docs/debugAPI/README.html"
    weight = 3

#[[menu.main]]
#    name = "Home"
#    url = "/"
#    weight = 1

#[[menu.main]]
#    name = "Docs"
#    url = "/docs/"
#    weight = 2


[params]
  google_analytics_id=""
  homepage_button_link = '/bee-docs/introduction.html'
  homepage_button_text = 'Swarm Docs'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/swarm-logo.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/swarm.png"
